baseURL = "https://arthur.afarias.org/"
languageCode = "en-us"
title = "Arthur Farias"
theme = "beautiful-custom"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentOptions = "linenos=table"
#disqusShortname = "arthur-afarias-org"
googleAnalytics = "UA-137868927-1"

[Params]
  subtitle = "Electrical Engineering Student and Enthusiast Developer"
  logo = "img/profile.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  selfHosted = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  name = "Arthur de Araújo Farias"
  website = "arthur.afarias.org"
  email = "arthur@afarias.org"
  # facebook = "arthurafarias"
  # googleplus = "+arthurafarias" # or xxxxxxxxxxxxxxxxxxxxx
  github = "arthurafarias"
  gitlab = "arthurafarias"
  # twitter = "arthurafarias"
  reddit = "arthurafarias"
  linkedin = "arthurafarias"
  # xing = "arthurafarias"
  stackoverflow = "users/1526039/arthur-afarias"
  # snapchat = "arthurafarias"
  # instagram = "arthurafarias"
  # youtube = "user/arthurafarias" # or channel/channelname
  # soundcloud = "username"
  # spotify = "arthura"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "arthurafarias"
  # telegram = "arthurafarias"

[[menu.main]]
    name = "Blog"
    url = "post/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
